'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
      </main>
    </>
  );
}